############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Service"
url = "service/"
weight = 3

[[main]]
hasChildren = true
name = "Industries"
weight = 4

[[main]]
name = "Medical"
parent = "Industries"
url = "industry/medical/"

[[main]]
name = "Dental"
parent = "Industries"
url = "/industry/dental/"

[[main]]
name = "Radiology"
parent = "Industries"
url = "industry/radiology/"

[[main]]
name = "SMB"
parent = "Industries"
url = "industry/smb/"

[[main]]
name = "Enterprise"
parent = "Industries"
url = "industry/enterprise/"

[[main]]
name = "Non-Profit"
parent = "Industries"
url = "industry/non-profit/"

[[main]]
name = "Hospitality"
parent = "Industries"
url = "industry/hospitality/"

[[main]]
name = "Restaurant"
parent = "Industries"
url = "industry/restraurant/"

#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 4

#[[main]]
#name = "Team"
#url = "team/"
#weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 5

#[[main]]
#hasChildren = true
#name = "Pages"
#weight = 8

#[[main]]
#name = "Project"
#parent = "Pages"
#url = "project/"

#[[main]]
#name = "Pricing"
#parent = "Pages"
#url = "pricing/"

#[[main]]
#name = "Elements"
#parent = "Pages"
#url = "elements/"

# footer menu
[[footer]]
#name = "Legal"
#url = "#"
#weight = 1

[[footer]]
#name = "Sitemap"
#url = "#"
#weight = 2

#[[footer]]
#name = "Privacy Policy"
#url = "#"
#weight = 3

#[[footer]]
#name = "Terms & Conditions"
#url = "#"
#weight = 4
